/**
 * tests/e2e/screens/_contract.ts — screen-contract harness.
 *
 * Every design screen (agents/design/return/…/screens/<ID>/SPEC.md) gets a spec under
 * tests/e2e/screens/<ID>.spec.ts generated by `pnpm screen:scaffold <ID>`. The
 * generated file uses `describeScreen()` which contributes the *contract* tests
 * every screen must pass, and leaves per-state / per-action tests as `test.fixme`
 * for the implementing agent to fill in. A screen WP cannot move to `review`
 * while any fixme remains (enforced by `pnpm screen:audit`).
 *
 * Contract tests contributed automatically:
 *   1. renders at every viewport without console errors / failed requests
 *   2. dark mode renders (data-theme=dark) and differs from light
 *   3. axe: no serious/critical violations (light + dark)
 *   4. every `data-testid` listed in the SPEC exists on the default state
 *   5. permitted roles reach the route; every other seeded role is refused (403/redirect)
 *   6. touch density: all interactive targets ≥ 48×48 at the mobile viewport
 *
 * Why so strict: the design system's value is uniformity; regressions in one
 * screen are invisible unless every screen asserts the same invariants.
 */
import { test, expect, type Page, type BrowserContext } from '@playwright/test'
import { signIn } from '../_helpers'

// Seeded personas (scripts/db-seed.mjs). Extend when new roles are seeded.
export const PERSONAS: Record<string, string> = {
  super_admin: 'sasha@bulwark.platform',
  org_admin: 'drew@bulwark.demo',
  org_manager: 'morgan@bulwark.demo',
  field: 'matthew@bulwark.demo',
  sub_contractor: 'jeff@bulwark.demo',
  viewer: 'vivian@bulwark.demo',
  homeowner: 'homer@bulwark.demo',
  stakeholder: 'insurer@bulwark.demo',
}

export const VIEWPORTS = {
  desktop: { width: 1440, height: 900 },
  tablet: { width: 1024, height: 768 },
  mobile: { width: 390, height: 844 },
} as const
export type ViewportName = keyof typeof VIEWPORTS

export interface ScreenContract {
  /** Design ID, e.g. AD-12 */
  id: string
  /** Concrete route to open for the default state (ids resolved via `resolveRoute`) */
  route: string | ((ctx: { page: Page }) => Promise<string>)
  /** Roles allowed per SPEC "Roles:" line */
  roles: string[]
  /** Public screens such as login do not require or gate on an authenticated role. */
  publicRoute?: boolean
  /** Viewports to assert; FD/SC screens add 'tablet' */
  viewports?: ViewportName[]
  /** data-testid values the SPEC names for the default state */
  testIds?: string[]
  /** axe rule ids to skip with justification, e.g. { 'color-contrast': 'ED-xxx: brand accent override' } */
  axeAllow?: Record<string, string>
  /** Optional setup executed after sign-in (seed data, navigate to fixture) */
  setup?: (ctx: { page: Page; context: BrowserContext }) => Promise<void>
}

export async function setTheme(page: Page, theme: 'light' | 'dark') {
  await page.addInitScript((t) => {
    try { localStorage.setItem('bulwark.theme', t) } catch { /* ignore */ }
    document.documentElement.setAttribute('data-theme', t)
  }, theme)
}

async function collectRuntimeErrors(page: Page) {
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`))
  page.on('console', (m) => { if (m.type() === 'error') errors.push(`console: ${m.text()}`) })
  page.on('requestfailed', (r) => { if (!/favicon|hot|__nuxt_devtools/.test(r.url())) errors.push(`requestfailed: ${r.url()} ${r.failure()?.errorText}`) })
  return errors
}

interface AxeViolation { id: string; impact?: string; help: string; nodes: { target: string[] }[] }
interface AxeBuilderLike { disableRules(rules: string[]): AxeBuilderLike; analyze(): Promise<{ violations: AxeViolation[] }> }

export async function assertAxeClean(page: Page, allow: Record<string, string> = {}) {
  let AxeBuilder: (new (opts: { page: Page }) => AxeBuilderLike) | undefined
  try { ({ default: AxeBuilder } = await import('@axe-core/playwright') as unknown as { default: new (opts: { page: Page }) => AxeBuilderLike }) } catch {
    throw new Error('@axe-core/playwright is required for screen-contract tests')
  }
  const results = await new AxeBuilder!({ page }).disableRules(Object.keys(allow)).analyze()
  const serious = results.violations.filter((v) => v.impact === 'serious' || v.impact === 'critical')
  expect(serious, serious.map((v) => `${v.id}: ${v.help} (${v.nodes.length} nodes)\n  ${v.nodes.slice(0, 3).map((n) => n.target.join(' ')).join('\n  ')}`).join('\n')).toEqual([])
}

export async function assertTouchTargets(page: Page, min = 48) {
  const offenders = await page.evaluate((min) => {
    const sel = 'a[href], button, input:not([type=hidden]), select, textarea, [role=button], [role=tab], [role=menuitem], [role=switch], [role=checkbox]'
    const out: string[] = []
    for (const el of Array.from(document.querySelectorAll<HTMLElement>(sel))) {
      const r = el.getBoundingClientRect()
      if (r.width === 0 || r.height === 0) continue // hidden
      if (el.closest('[data-density="compact"]')) continue
      // chips inside ≥48px rows are allowed (A6-CHECKLIST note)
      if (el.closest('[data-touch-row]')) continue
      if (r.width < min || r.height < min) out.push(`${el.tagName.toLowerCase()}${el.getAttribute('data-testid') ? `[data-testid=${el.getAttribute('data-testid')}]` : ''} ${Math.round(r.width)}×${Math.round(r.height)}`)
    }
    return out
  }, min)
  expect(offenders, `interactive targets under ${min}px:\n${offenders.join('\n')}`).toEqual([])
}

export async function resolveRoute(page: Page, route: ScreenContract['route']) {
  return typeof route === 'function' ? route({ page }) : route
}

export function describeScreen(contract: ScreenContract, extra?: () => void) {
  const viewports = contract.viewports ?? ['desktop', 'mobile']
  const primaryRole = contract.roles[0]
  if (!contract.publicRoute && !primaryRole) throw new Error(`${contract.id}: screen contract requires an explicit persona`)

  test.describe(`${contract.id} — screen contract`, () => {
    test.beforeEach(async ({ page, context }) => {
      if (!contract.publicRoute) await signIn(context, PERSONAS[primaryRole!] ?? primaryRole!)
      await contract.setup?.({ page, context })
    })

    for (const vp of viewports) {
      test(`renders at ${vp} (${VIEWPORTS[vp].width}px) without runtime errors`, async ({ page }) => {
        const errors = await collectRuntimeErrors(page)
        await page.setViewportSize(VIEWPORTS[vp])
        await page.goto(await resolveRoute(page, contract.route))
        await expect(page.locator('main, [role=main]').first()).toBeVisible()
        expect(errors).toEqual([])
      })
    }

    test('dark mode renders tokenized surfaces (not a filter)', async ({ page }) => {
      await page.setViewportSize(VIEWPORTS.desktop)
      const route = await resolveRoute(page, contract.route)
      await setTheme(page, 'light'); await page.goto(route)
      const light = await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--bg-card').trim())
      await setTheme(page, 'dark'); await page.goto(route)
      const dark = await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--bg-card').trim())
      const filter = await page.evaluate(() => getComputedStyle(document.documentElement).filter)
      expect(dark).not.toEqual(light)
      expect(filter === 'none' || filter === '').toBeTruthy()
    })

    for (const theme of ['light', 'dark'] as const) {
      test(`axe: no serious/critical violations (${theme})`, async ({ page }) => {
        await page.setViewportSize(VIEWPORTS.desktop)
        await setTheme(page, theme)
        await page.goto(await resolveRoute(page, contract.route))
        await assertAxeClean(page, contract.axeAllow)
      })
    }

    if (contract.testIds?.length) {
      test('exposes every SPEC test id in the default state', async ({ page }) => {
        await page.setViewportSize(VIEWPORTS.desktop)
        await page.goto(await resolveRoute(page, contract.route))
        for (const id of contract.testIds!) await expect(page.getByTestId(id).first(), id).toBeAttached()
      })
    }

    if (viewports.includes('mobile')) {
      test('touch density: interactive targets ≥ 48px at 390', async ({ page }) => {
        await page.setViewportSize(VIEWPORTS.mobile)
        await page.goto(await resolveRoute(page, contract.route))
        await assertTouchTargets(page)
      })
    }

    if (contract.publicRoute) {
      test('anonymous visitors can reach the public route', async ({ page }) => {
        const response = await page.goto(await resolveRoute(page, contract.route))
        expect(response?.status() ?? 200).toBeLessThan(400)
      })
    } else {
      test.describe('role gate', () => {
        for (const [role, email] of Object.entries(PERSONAS)) {
          const allowed = contract.roles.includes(role)
          test(`${role} is ${allowed ? 'allowed' : 'refused'}`, async ({ browser }) => {
            const context = await browser.newContext()
            try {
              await signIn(context, email)
              const page = await context.newPage()
              const route = await resolveRoute(page, contract.route)
              const res = await page.goto(route)
              if (allowed) {
                expect(res?.status() ?? 200).toBeLessThan(400)
                await expect(page).not.toHaveURL(/\/(403|login)/)
              } else {
                await expect(page).toHaveURL(/\/(403|login)|\/$/)
              }
            } finally {
              await context.close()
            }
          })
        }
      })
    }

    extra?.()
  })
}
